# Options Introduction


The purpose of the chapter is to introduce options as painlessly as possible.

Options are simple contracts that show up everywhere in finance.  They can be viewed as the building block of many other financial instruments.  The theory of option pricing lies at the foundation of much of quantitative finance.

Options are insurance contracts wrapped around other financial assets.  The asset that is being insured is called the *underlying*.  The underlyings we are going to consider in this book will be stocks and ETFs, but the essential concepts are the same for other underlyings such as interest rates, corn futures, or barrels of oil.

Let's build some intuition by considering a type of insurance that you are probably familiar with: car insurance.


## Car Insurance

Wolverine Trading is a successful market-making firm based in Chicago. Following the lead of billionaire Warren Buffet, who's major cash-cow is GEICO, the partners at Wolverine are interested in getting into the car insurance business. They have hired us as consultants to help devise a pricing policy for this business.


The type of underlying that Wolverine would like to insure is: a specific driver coupled with a specific vehicle.  The driver that is being insured is going to pay Wolverine *premium*.  In exchange for the premium, Wolve will reimburse the driver whenever damage to the care exceeds a certain dollar amount, called the *strike* of the contract.


**Intuition Check:** Do you think that Wolverine should charge the same premium irrespective of the underlying?  Why or why not?

After some deliberation, we have arrive upon the following underlying characteristic to base price differentiation on.

#### **Price of Underlying** {-}

Sandra is a prospective customer; she has two vehicles that she wants to switch over.   One is a busted old Mazda 3 that she bought when she was a struggling graduate student.  The other is a fancy self-driving Tesla she bought after starting her lucrative options trading career.

-ADD SIDE BY SIDE PICTURES HERE-

**Intuition Check:** Which car should be more expensive to insure?  Why?


#### **Strike Price of Contract** {-}

Wolverine has three different strike prices that they can offer Sandra Tesla:

  - at-the-money $:=$ \$0
  - \$1,000
  - \$5,000


**Exercise:** Order the premium for the three strike prices from cheapest to most expensive.


#### **Time to Expiration** {-}

Wolve has three different strike prices they can offer to Sandra for her Tesla:

  - 0.25 years
  - 0.50 years
  - 1.00 years

**Exercise:** Order the premium for the three tenors from cheapest to most expensive.


#### **Voltility of Underlying** {-}

Wolve is pricing insurance for two different customers, Sally and Patty. Both are looking to purchase insurance a fancy new self-driving Tesla.   They both want a 1-year contract with with a $1,000 strike price.  Sally's friends describe her as calm, chill, responsible, quiet, serene.  On the other hand, Patty's friends describe her: wild, hyper, flakey, loud, and **volatile**.
 
**Intuition Check:** Who should Wolverine charge more for insurance? Why?


#### **Insurance Payoff Graph** {-}

It's 8 a.m. on a Saturday morning.  Sally is driving on the freeway heading to her Crossfit class: hands at 10-and-2, eyes intently on the road, soothing classical music playing in the background.

Patty is also driving on the freeway, making her way home from an all night rave.  As she drives, she touches up her makeup and then snaps a few selfies for her IG stories (morning car selfies have the *best* light..OMG).

<!-- she has a cigarette in one hand, and with the other she is some snapping some selfies for her IG story - morning car selfies have the *best* light. -->


Suddenly, Patty loses control and swerves in front of Sally. Patty is riding dirty and has no insurance, but responsible Sally a made sure to switch over to a \$1000-strike Wolverine policy.  Here is a graph of the *payoff* to her insurance contract immediately following the accident.


```{r, sally_insurance_payoff}
strike <- 1000 
damage <- seq(0, 3000, 500)
payoff <- pmax(damage - strike, 0)
heading <- "insurance payoff"
plot(damage, payoff, type = "n", main = "Payoff to Sally")
lines(damage, payoff, type = "l")
```


Notice that if the damage is less than the \$1,000 strike price, Sally recieves no reimbursement from her insurance.  For every dollar over the strike price, Sally recieves a one-for-one payout.  The options we study in the book behave similarly.
