# Preliminaries

In this section I develop the basic results from quantitative finance that will be needed later in the book.  For a more detailed treatment, I recommend the following execellent texts:

**Options, Futures, and Other Derivatives** by John C. Hull

**Derivative Markets** by Robert L. McDonald


## Discounting & Accumulating

When you lend money, you are paid interest to compensate for the fact that you can't use the money to lent for other purposes. In this book I assume loans are totally safe and there is no risk of default.  It is useful to the of the loan amount accumulating with interest. I use the following notation and nomenclature to capture this idea of accumulation:

**Definition:** Assume the current time is $t$ and that $T$ is some time in the future. Then one dollar will accumulate to $A(t,T)$ by time $T$.  I will call $A(t,T)$ an *accumulation factor*.

If you are going to recieve money in the future, it's not really worth as much to you as if the money were paid right now.  The way we account for this value difference is by essentially *discounting* by the amount of interest you could have earned between now when you are going to be paid. The is the notion of present value and I express it as follows:


**Definition:** The time $t$ present value of a one dollar cashflow at time $T$ will be denoted by $D(t,T)$. I will call $D(t,T)$ a discount factor. I will call $D(t, T)$ a *discount factor*.


The following statements are true:

1. $A(t,T) \geq 1$.

2. $D(t, T) \leq 1$.

3. $D(t,T) = A(t,T)^{-1}$.




## Stocks and Dividends

## ETFs

## Forward Contracts

<!-- Now you have learned the very basic concepts of R Markdown. The idea should be simple enough: interweave narratives with code in a document, knit the document to dynamically generate results from the code, and you will get a report. This idea was not invented by R Markdown, but came from an early programming paradigm called "Literate Programming" [@knuth1984]\index{Literate Programming}. -->

<!-- Due to the simplicity of Markdown and the powerful R language for data analysis, R Markdown has been widely used in many areas. Before we dive into the technical details, we want to show some examples to give you an idea of its possible applications. -->

### Synthetic Forwards

A portfolio consisting of a long call and a short put is a synthetic forward position.


Let the current time be $t$.  Consider a call and put on the same underlying, with the same strike price $K$, that both expire at time $T$.  If you have a long position in the call and a short position in the put, then in all states of the world at time $T$ this portfolio has a value of $S_{T} - K$, which is the same value as the payoff as a long forward.

Suppose that $S_{T} > K$. You exercise your long call, for which you recieve the stock worth $S_{T}$ whilie paying the strike price $K$ for it. The put you are short expires worthless. The total value of these two positions is $S_{T} - K$.

On the other hand, suppose $S_{T} < K$. Your short put postion will be exercised, forcing you to buy the stock for $K$ even though it is only worth $S_{T}$.  Your call is worthless, so you won't exercise.  Once again, the combined value of these two position is $S_{T} - K$.

If $S_{T} = K$, nothing happens because both options are worthless. Doing nothing has zero value.  But of course in this situation we have that $S_{T} - K = 0$.


## Put-Call Parity
\begin{align*}
C(t, T, K) - P(t, T, K) = D(t, T)(F(t, T) - K)
\end{align*}


