# Profit & Loss

Daily profit and loss is one of the most basic and important performance measure of an investment or trading strategy.  In this chapter we detail how to calculate profit and loss for stock and options trades.

## Stock PNL

## Option PNL
Suppose you trade an option $\mathcal{O}$ at a price $P$ on trade-date $t_{1}$. Suppose you hold the option until expiration, which is trade-date $t_{n}$.  The letter $i$ will serve as an index over the trade-dates, so $i = 1,\ldots,n$. 

Let $B_{i}$ and $A_{i}$ be the end-of-day bid and ask prices of the option for trade-date $t_{i}$. Note that $B_{n} = A_{n} =$ option-payoff.  We seek to define the following:  

**Daily:** $D_{i}$ -  the *daily PNL* for the trade as of end-of-day $t_i$.  

**TTD:** $C_{i}$ - the *trade-to-date PNL* for the trade as of end-of-day $t_i$.

Intuitively, the trade-to-date (TTD) PNL is the amount of money you made or lost if you unwind the trade at current market values.  The daily PNL is the one day change in the trade-to-date PNL.  The two concepts are interchangable in that it is possible to define TTD PNL in terms of daily PNL and vice-versa.

In my own work, I find it most useful to calculate daily PNLs of each trade, and then define the cummulative PNL as the sum of the dailies.  I present all both alternative below, for both buys and sells.

#### TTD as Sum of Daily - Buy {-}


\begin{align*}
D_{i} &= \begin{cases} B_{1} - P & i = 1 \\ B_{i} - B_{i-1} & i > 1 \end{cases} \\[10pt]
C_{i} &= \sum_{k=1}^{i} D_{k}
\end{align*}

&nbsp;

**Exercise:** Show that $C_{j} = B_{j} - P$. 


#### TTD as Sum of Daily - Sell {-}


\begin{align*}
D_{i} &= \begin{cases} P - A_{1} & i = 1 \\ A_{i-1} - A_{i} & i > 1 \end{cases} \\[10pt]
C_{i} &= \sum_{k=1}^{i} D_{k}
\end{align*}

&nbsp;

**Exercise:** Show that $C_{i} = P - A_{i}$. 


#### Daily as Change in TTD - Buy {-}


\begin{align*}
C_{i} &= B_{i} - P \\[10pt]
D_{i} &= \begin{cases} C_{1} & i = 1 \\ C_{i} - C_{i-1} & i > 1 \end{cases}
\end{align*}

&nbsp;

**Exercise:** Show that both formulations of $D_{i}$ are equivalent.


#### Daily as Change in TTD - Sell {-}


\begin{align*}
C_{i} &= P - A_{i} \\[10pt]
D_{i} &= \begin{cases} C_{1} & i = 1 \\ C_{i} - C_{i-1} & i > 1 \end{cases}
\end{align*}

&nbsp;

**Exercise:** Show that both formulations of $D_{i}$ are equivalent.

## Scaling Up
It is rare that we will calculuate the PNL of a single stock trade or options trade. Rather, we will want to calculate the PNL of a portfolio of trades.  This is a trivial matter, as the daily PNL of a collection of trades is simply the sum of the daily PNL of the individual trades.

[CODING EXERCISE]


## Returns

While PNL is an important performance metric, it is often hard to interpret with first normalzing by the amount of capital required to fund the investment.  This is precisely what the notion of a return is.  We will let $R_{i}$ be the day $t_{i}$ be the return of a trading strategy
